version: '3.0'

networks:
  app-global:
    external: true

services:
  tools-api:
    container_name: familyplannercore
    image: familyplannercore:latest
    ports:
      - 7001:7001
    networks:
      - app-global