# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for Nuget packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for containers
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for containers
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
