# https://taskfile.dev

version: '3'

includes:
  app:
    taskfile: ./FamilyPlanner.Core/Taskfile.yml
    dir: ./FamilyPlanner.Core
  web:
    taskfile: ./FamilyPlanner.Blazor/Taskfile.yml
    dir: ./FamilyPlanner.Blazor

